Feature #74 - Additional columns in Record Manager views
maykinmedia/archiefvernietigingscomponent pull request #175
Opened 2021-03-11 13:06 UTC by SilviaAmAm

Fixes #74

2021-03-15 15:29 UTC, annashamray requested changes

2021-03-16 10:49 UTC, SilviaAmAm commented on src/archiefvernietigingscomponent/sass/components/_destruction-create.scss
> +    width: 15%;
![Screenshot from 2021-03-16 11-47-03](https://user-images.githubusercontent.com/19154114/111296974-63ce4b80-864d-11eb-9314-1ac2cc32b13b.png)

I ended up making the white background larger, reduced the font size a bit, fixed the width of the columns and added some word-break property to the filters. Hopefully it looks better now with the long zaaktypes!

2021-03-17 12:01 UTC, annashamray approved these changes
Looks very nice now

2021-03-17 12:01 UTC, annashamray commented on src/archiefvernietigingscomponent/sass/components/_destruction-create.scss
> +    width: 15%;
Yes, it looks much neater

2021-03-22 08:17 UTC, merged