Feature #58 - Audit trail report
maykinmedia/archiefvernietigingscomponent pull request #209
Opened 2021-04-07 16:29 UTC by SilviaAmAm

Fixes #58

2021-04-08 08:50 UTC, SilviaAmAm commented
An example of the PDF report with the Audit trail:
![Screenshot from 2021-04-08 10-45-42](https://user-images.githubusercontent.com/19154114/113997173-2cbc1600-9858-11eb-886b-0c46d536965b.png)

2021-04-12 16:20 UTC, annashamray requested changes
Nice implementation with reusing audit trails! 

The only thing which is bothering me - zaak identifications are not specified in most log entries (creating, updating and reviewing the destruction list).
For example, a record manager created a DL with two zaken A and B
The reviewer asks to remove the zaak A, and the record manager excludes it. 
If they have not specified the identificatie of the zaak A in their comments, archivaris will never find out what particular zaak was excluded from the DL
I don't know if it's a necessary information or not and if it should be added to the audit trails

2021-04-12 16:20 UTC, annashamray commented on src/archiefvernietigingscomponent/report/templates/report/audittrail/audittrail.html
> +<h2>Audit trail</h2>
I think the "Audit trail" header should be formatted in the same way that a table header above (or be a little smaller, but not bigger)

2021-04-13 09:12 UTC, SilviaAmAm commented on src/archiefvernietigingscomponent/destruction/management/commands/convert_log_templates.py
> +                    log.save()
This one-liner is beautiful

2021-04-13 09:20 UTC, SilviaAmAm commented on src/archiefvernietigingscomponent/destruction/templates/destruction/logs/item_destruction_failed.html
> +    </p>
Currently only the `aborted.html`, `created.html`, `review_created.html` and `updated.html` are used for the audit-trail report, but I renamed them all to `.html` to be consistent!

2021-04-13 15:14 UTC, SilviaAmAm commented on src/archiefvernietigingscomponent/destruction/templates/destruction/logs/aborted.html
> +    <strong>[{{ log.timestamp|date:'Y-m-d H:i' }}]:</strong>
I made an issue for this (https://github.com/maykinmedia/archiefvernietigingscomponent/issues/222): I need to figure out how to nicely handle CSS with weasyprint, for when the HTML is converted to a PDF.

2021-04-13 15:21 UTC, SilviaAmAm commented
Latest version of the report :)
![Screenshot from 2021-04-13 17-19-44](https://user-images.githubusercontent.com/19154114/114577747-92573a80-9c7c-11eb-823f-065c1c91248d.png)

2021-04-19 08:13 UTC, annashamray approved these changes
Very nice!

2021-04-19 08:14 UTC, merged