Feature #78 - Filters record manager
maykinmedia/archiefvernietigingscomponent pull request #212
Opened 2021-04-08 14:50 UTC by SilviaAmAm

Fixes #78

2021-04-12 15:19 UTC, annashamray requested changes
DL filtering looks very nice! 

But I have some remarks about email preferences implementation since I haven't reviewed them. if you want they can be dealt with in a separate issue/PR.
* if the record-manager doesn't have email preferences configured, then the destruction-list page will return 500 error. The same applies to a reviewer list page. I think data migration is needed here. 
* `EmailPreference` model is not included into `admin_index` fixture
* it would be nice to have email preferences as inlines\field in the detail page and included into the `list_display` in the User admin (I don't quite understand why email preferences are put into a separate model. tbh)

2021-04-12 15:19 UTC, annashamray commented on src/archiefvernietigingscomponent/destruction/filters.py
> +                ~Q(author=F("assignee")) | Q(assignee__isnull=True),
```suggestion
                Q(~Q(author=F("assignee"), status=ListStatus.in_progress) | Q(status=ListStatus.processing),
```
I'm not sure but I thought that `Q(assignee__isnull=True)` is a special case of `~Q(author=F("assignee"))` and is excessive
And I know that theoretically, an author can't be an assignee if `status=ListStatus.processing`, but still this case should be included in this `if`

2021-04-12 15:58 UTC, SilviaAmAm commented
@annashamray I shall address the issues with the email preferences in another PR! :) But to clarify:
- Currently there is a signal that whenever a new user is created, it adds email preferences for that user. So any new user should have the email preferences. Maybe we should have a management command that checks for any old users without email preferences and creates them in case they are missing?
- I shall add it!
- Would it be better to add an email preference field to the user instead of having a separate model? Initially I thought it would be more flexible in case additional email preferences need to be added in the future, but in the end if it's just a single choice field I agree that it is maybe a bit overkill :P

2021-04-12 16:01 UTC, annashamray commented
>     * Currently there is a signal that whenever a new user is created, it adds email preferences for that user. So any new user should have the email preferences. Maybe we should have a management command that checks for any old users without email preferences and creates them in case they are missing?

I think data migration should be enough. It should be run only once and if it's a migration it won't depend on humans :)

2021-04-15 14:33 UTC, annashamray approved these changes

2021-04-15 16:20 UTC, merged